name: 'Ascend audit setup'
description: 'Ascend audit setup recipe - installs modules and sets up config'
type: 'Content type'
recipes:
  # Can't depend on other recipes outside of this dir or core!
install:
  - config_pages
  - profile
  - views_argument_token
  - views_relationship_condition
  - ascend_audit
config:
  strict: true
  import:
    ascend_audit: '*'
  actions:
