name: 'Ascend audit setup'
description: 'Ascend audit setup recipe - installs modules and sets up config'
type: 'Content type'
recipes:
  # Can't depend on other recipes outside of this dir or core!
install:
  - config_pages
  - profile
  - views_argument_token
  - views_relationship_condition
  - ascend_audit
config:
  strict: true
  import:
    ascend_audit: '*'
  actions:
    core.entity_form_display.taxonomy_term.category.default:
      setComponent:
        name: ascend_standards
        options:
          type: cshs
          weight: 3
          region: content
          settings:
            save_lineage: false
            force_deepest: true
            parent: null
            level_labels: 'Standard, Aspect'
            hierarchy_depth: 0
            required_depth: 0
            none_label: '- Please select -'
          third_party_settings: {  }
