name: 'Ascend audit setup'
description: 'Ascend audit setup recipe - installs modules and sets up config'
type: 'Content type'
recipes:
  # Can't depend on other recipes outside of this dir or core!
install:
  - ascend_school
  - ascend_audit
  - ascend_ap
  # Comment/entity_print modules are installed here BUT config'd in audit_ap.
  # Means we can centralise our contrib modules in this ascend_audit repo.
  - comment
  - comment_notify
  - config_pages
  - entity_print
  - entity_print_views
  - profile
  - views_argument_token
  - views_relationship_condition
  - fmm_views_edit_link
config:
  strict: true
  import:
    ascend_school: '*'
    ascend_audit: '*'
    ascend_ap: '*'
  actions:
    form_mode_manager.links:
      simpleConfigUpdate:
        local_tasks.audit:
          position: primary
        local_tasks.ap:
          position: primary
    content_lock.settings:
      simpleConfigUpdate:
        types.ap:
          '*': '*'
        types.audit:
          '*': '*'
        types.school:
          '*': '*'
        form_op_lock.ap:
          mode: 0
          values: {  }
        form_op_lock.audit:
          mode: 0
          values: {  }
        form_op_lock.school:
          mode: 0
          values: {  }
    core.entity_form_display.taxonomy_term.category.default:
      setComponent:
        name: ascend_standards
        options:
          type: cshs
          weight: 7
          region: content
          settings:
            save_lineage: false
            force_deepest: true
            parent: null
            level_labels: 'Standard, Aspect'
            hierarchy_depth: 0
            required_depth: 0
            none_label: '- Please select -'
          third_party_settings: {  }
    user.role.user_manager:
      grantPermissions:
        - 'assign auditor role'
        - 'assign adviser role'
        - 'assign audit_manager role'
        - 'access profile overview'
        - 'access user profiles'
        - 'view user email addresses'
    user.role.site_manager:
      grantPermissions:
        - 'create terms in cluster'
        - 'create terms in rating'
        - 'create terms in standards'
        - 'edit terms in cluster'
        - 'edit terms in rating'
        - 'edit terms in standards'
